title: colinjfw
author: "Colin Walker"
url: "https://www.colinjfw.com"
description: Colin Walker | Team lead at Sendwithus. Code, devops and coffee.

icons:
  envelope: "mailto:me@colinjfw.com"
  twitter: "https://www.twitter.com/colinjfw"
  github: "https://github.com/colinjfw"
  book: https://medium.com/@colinjfw

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

plugins:
  - jekyll-seo-tag
