title: kodebrew
url: "https://kodebrew.com"
bio: Colin Walker | Team lead at Sendwithus. INTJ. Code, devops and coffee.

navigation_pages:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Reading List
    link: /reading
  - name: Github
    link: https://github.com/coldog
  - name: LinkedIn
    link: https://www.linkedin.com/in/cjwalker270
  - name: Twitter
    link: https://www.twitter.com/kodebrew

source: src
destination: dist

permalink: pretty

markdown: kramdown
gems:
  - jekyll-feed
