title: Colin Walker
baseurl: ""
url: "https://kodebrew.com"

navigation_pages:
  - name: Home
    link: /
  - name: Posts
    link: /posts
  - name: Reading List
    link: /reading
  - name: Github
    link: https://github.com/coldog
  - name: LinkedIn
    link: https://www.linkedin.com/in/cjwalker270
  - name: Twitter
    link: https://www.twitter.com/kodebrew

source: src
destination: dist

permalink: pretty

markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
