title: Colin Walker
baseurl: ""
url: "http://coldog.github.io"

navigation_pages:
  - name: Home
    link: /
  - name: Work
    link: /work
  - name: Email
    link: mailto:colinwalker270@gmail.com
  - name: Blog
    link: https://medium.com/@coldog
  - name: Github
    link: https://github.com/coldog
  - name: LinkedIn
    link: https://www.linkedin.com/in/cjwalker270

collections:
  work:
    output: true

permalink: pretty

markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
